const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 120,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "2",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 110,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "3",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 100,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "4",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 115,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "5",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 111,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
    {
      _id: "6",
      name: "Nike Slim Shirt",
      category: "Shirt",
      image: "/images/s1.png",
      price: 123,
      countInStock: 10,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      description: "High Quality Product",
    },
  ],
};

export default data;
